ローカルサーバーを一時的に立てて認可コードを自動的に処理できるコードを追加
cm-kazup0n/aurl-rust pull request #58
Opened 2022-07-22 07:52 UTC by komuro-hiraku

# 内容

- feat: code=XXX を抽出できる正規表現パターンを追加
- feat: 標準入力を待ち構えていたコードを廃止、サーバーで抽出した認可コードを処理に利用するように変更
- feat: 追加した正規表現パターンのテストコードを追加

2022-07-22 08:27 UTC, komuro-hiraku commented on src/oauth2.rs
> +        GrantType::pkce_challenge(PkceMethod::S256, "a".repeat(129).as_str());
ここついでになおしました

2022-07-24 05:48 UTC, cm-kazup0n requested changes
ウェブサーバと認可コードのパースは別モジュールにしておくれ。oauth2.rsは既に十分にでかいので。

2022-07-24 05:52 UTC, cm-kazup0n requested changes

2022-07-24 05:52 UTC, cm-kazup0n commented on src/oauth2.rs
> +                            let mut params = first_line.split_whitespace();
認可コード抜き出すのはまるっとpath_utilにつっこんだほうがいいと思う。テストしやすいし。

2022-07-24 05:52 UTC, cm-kazup0n commented on src/oauth2.rs
> +                            error!("Callback Server error");
エラーの詳細もログに出してほしい

2022-08-17 04:23 UTC, cm-kazup0n approved these changes

2022-08-21 13:33 UTC, merged